### ISSUE TITLE
System halted issue

### ISSUE THREAD

**Issue by Ilovemyhous** [PartialVolume/shredos.x86_64#102]
Hello!
I was trying to wipe to wipe 5 HDD’s at the same time, 4 being SATA, and one being connected trough USB.
**System halted.**

I tried a few things here and there, now I only have one SATA HDD plugged in, still **System halted**.

The system W3530 Xeon CPU, 6GB of RAM. But only supports Legacy boot. I tried to boot on another system (*in Legacy mode*) it works.

ShredOS version: `2021.08.2_21_x86-64_0.32_023_20220126`
I also verified the SHA1, and it’s the same as on the release page.

Exact crash dump.
![74D7A5F5-9BDB-4858-9819-2EC7DA0E80BB](https://user-images.githubusercontent.com/50217071/164186571-d044d14b-fdf9-4720-ac86-cc4f85a816b2.jpeg)

**Comment by PartialVolume** [comment]
Can you run [memtest86](https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.memtest86.com/&ved=2ahUKEwiL2uPXt6L3AhUIonIEHYwMA18QFnoECBQQAQ&sqi=2&usg=AOvVaw2hpSfQL2mRiv8-CXaB3LPO) maybe do an overnight test on the CPU memory to see if it shows up any errors.

**Comment by PartialVolume** [comment]
Apart from CPU memory it could also be that the USB port is causing corruption of the compressed kernel. Try different USB ports and if they all fail then if the system has a CD/DVD drive try booting from that using the .iso ShredOS image.

If it doesn't have a CD/DVD drive then burn the .img file to one of the SATA drives you are going to wipe, put it back in the system and boot from it. If it boots you can then wipe the drive you booted from plus all the others simultaneously. ShredOS loads itself fully into CPU memory so ShredOS's operation won't be affected if you wipe the disc ShredOS booted from.

**Comment by Ilovemyhous** [comment]
Hello!
So after trying a bunch of things, it turns out, it was a faulty drive, which has *apparently* 0GB. Removing the drive from the system makes it work.
I tried booting from my existing Linux distro, and it didn’t worked, and the BIOS has some serious issues too, until I removed the drive.
Idk how it managed to be a 0GB drive, but thank you anyway for your help!

**Comment by PartialVolume** [comment]
No, problem. Glad you sorted it and thanks for letting us know what the cause of the issue was.
