### ISSUE TITLE
Little mistake at the ShredOS img flash guide for MAC users

### ISSUE THREAD

**Issue by MichalPlays** [PartialVolume/shredos.x86_64#11]
At
" Obtaining and writing shredos to a USB flash drive, the easy way ! "
under the section "Linux (and MAC) users" 

there is written something like 
_(where sdx is the device name of your USB drive, this can be obtained from the results of sudo fdisk -l)_

I don't know if that's is happening after the MacOS Big Sur update or something but the command sudo fdisk -l doesn't work on MacOS. It just gives me this error "fdisk: illegal option - l"

Please add to the installation guide that the fdisk command should be used on Linux and for MAC users should use the **diskutil list** command in order to display all storage devices connected to your machine.

Here is the screenshot, what happens is if I type the fdisk command from the readme file and what happens if you type the diskutil command I mentioned before, in case you don't own any device that runs MacOS and you might think that this command formats the hard drive

<img width="643" alt="Bildschirmfoto 2020-12-08 um 14 38 20" src="https://user-images.githubusercontent.com/14944933/101490925-55440a00-3963-11eb-9b00-be4d6fc80ed2.png">

Sorry for my bad English and I hope to see some correction made in the readme file : )

**Comment by PartialVolume** [comment]
Thanks for the update, I'll make the changes ASAP.

**Comment by MichalPlays** [comment]
Alright, thanks for the Info

**Comment by PartialVolume** [comment]
README.md updated. Thanks for your feedback, much appreciated.
