### ISSUE TITLE
Kernel panic booting into shredos on Dell r440

### ISSUE THREAD

**Issue by Cody-Coleman** [PartialVolume/shredos.x86_64#112]
When using any version after Shredos shredos-2020.05.017_x86-64_0.32.003_20211111.img (or iso) on a Dell R440, after loading the shredos into memory (so after the countdown reaches 100%) I get Kernal panic: 
Kernel panic - not syncing: Attempted to kill the idle task! 

Started with the latest release and I just kept trying earlier versions until I landed on the 05.017 version and I have had no issues with that. Not sure what other information you could use / need but this is very easy for me to reproduce. The other kicker is it's not all the Dell r440s doing this, and the bios/ firmware versions on those do not seem to matter (as two boxes with the same versions, one will work the other will not no matter what). But the r440s that this does work on seem to be the exception to the rule. 

![Screen Shot 2022-10-20 at 3 41 47 PM](https://user-images.githubusercontent.com/4247003/197229341-db20622a-b987-427f-84aa-7c08d254c857.png)

**Comment by PartialVolume** [comment]
Just wondering if you have tried toggling the x2APIC bios in in the processor section. According to the document below the virtualisation technology setting needs to be enabled to change the state of x2APIC. Are these settings different on the R440s that work as opposed to those that panic? Maybe worth trying to toggle the state of both these values and see if that makes any difference.

https://www.dell.com/support/manuals/en-uk/poweredge-r440/per440_bios_pub/processor-settings-details?guid=guid-ac6a729a-e608-44b1-affc-e024f94b28c9&lang=en-us

**Comment by c0nsaw** [comment]
Same issue with Dell R740xd2

**Comment by PartialVolume** [comment]
Can you add this to the *two* grub.cfg files in the kernel command line on the USB stick `initcall_blacklist=dw_i2c_init_driver` then give it another try. This seems to solve some Dell specific kernel panics.

**Comment by jarthur22** [comment]
Same issue on PowerEdge R720

**Comment by PartialVolume** [comment]
Take a look at [(https://lkml.iu.edu/hypermail/linux/kernel/2002.2/07364.html)](https://lkml.iu.edu/hypermail/linux/kernel/2002.2/07364.html) Looks pretty much identical to the snapshot at the top of this thread.

Not sure what the solution is as I've not followed through the whole thread but looks like it's all to do with APIC, is there something in the bios setup that will get around this problem like disabling it?

**Comment by PartialVolume** [comment]
>On the Dell PowerEdge T640/04WYPY, BIOS 2.4.8 11/27/2019, Linux 5.4.14 (and 4.19.57) with
> unset `IRQ_REMAP` and `X86_X2APIC` crashes on start-up, when x2APIC is enabled in the
> firmware.

Does disabling x2APIC in the firmware (I assume they are talking about the equivalent the BIOS??). Are you able to disable x2APIC on one of these Dell servers and see if it boots ShredOS?

**Comment by PartialVolume** [comment]
There is a x86_X2APIC option in the kernel and I don't have that enabled in ShredOS. If I build the current master with this x86_X2APIC option enabled are you able to test it on one of this Dell servers that are showing this problem?

If somebody can, then I'll upload a second .img that provides X2_APIC support.

**Comment by PartialVolume** [comment]
For reference x86_X2APIC is enabled in ShredOS by first enabling `ScaleMP vSMP` and then enabling the now visible `Support x2apic` and maybe also `Numascale NumaChip`.

**Comment by PartialVolume** [comment]
If you you able to try the latest pre-release version thanks. 

[v2021.08.2_23.2_x86-64_0.34](https://github.com/PartialVolume/shredos.x86_64/releases/tag/v2021.08.2_23.2_x86-64_0.34)

**Comment by chmuri** [comment]
@PartialVolume I have similar problem on dell r720xd with boot I have downloaded pre release but I can't boot from usb stick UEFI mode. Below screen with error.
![image](https://user-images.githubusercontent.com/19579448/232121657-c594c869-e005-4ce4-a9a8-d5edbaaf0fc5.png)

**Comment by PartialVolume** [comment]
@chmuri can you Alt F2 to display a virtual terminal?. Just wondering if the main terminal that nwipe runs in is hanging because of the raid controller. If you can bring up a virtual terminal then it's nothing to do with the direct rendering manager or graphics driver but might be due to the raid controllers.

If you can't bring up a terminal then maybe it's graphics. Can you telnet into the system after you get that message as per the instructions for headless systems. If it is graphics, ShredOS would have booted up behind the scenes. You will need to enable the telnet server and if you can login run dmesg and post the output.

Sorry, but I don't have access to any of that hardware so somebody is going to have to spend some time digging into this issue starting with the above methods.

**Comment by GrimDemon** [comment]
Hi @PartialVolume, I have the same problem on a DELL R640. Too bad you don't make a x64 ISO image for pre-releases. This would make it much easier to analyze the problem for people who remotely connect to their servers via iDRAC (it does not support remote booting via removable media). I was unable to convert the IMG file into a form that would allow me to run it as a bootable ISO image.

**Comment by PartialVolume** [comment]
@GrimDemon If you feel it may be useful I can build an .iso for the latest pre-release. May take a couple of days as I'm busy with other stuff at the moment. I'll let you know once it's been uploaded.

**Comment by OlivierFrancais** [comment]
I have same issue on Dell R440 and Dell R650xs, system is booting loaging Shredos and hang on a black screen. @PartialVolume  I'm available to make tests if you want

**Comment by PartialVolume** [comment]
@OlivierFrancais @GrimDemon @chmuri Can you try the latest pre-release. This contains the very latest linux firmware [v2021.08.2_23.4_x86-64_0.34](https://github.com/PartialVolume/shredos.x86_64/releases/tag/v2021.08.2_23.4_x86-64_0.34).

What graphics hardware is provided on these servers?

**Comment by chmuri** [comment]
Default graphics

**Comment by PartialVolume** [comment]
The default graphics card on a Dell R650xs is apparently a Matrox G200, I'm not sure what graphics are on the Dell R440, the spec I looked at did not mention anything about graphics.

Anyway, guess what, ShredOS is missing the G200 KMS (kernel mode setting) driver. It's also missing the AST driver for servers.

I'll add those two extra drivers and publish a new pre-release for testing.

**Comment by PartialVolume** [comment]
@c0nsaw For reference the Dell EMC PowerEdge R740xd2 also has a Matrox G200eW3 graphics controller. So hopefully the pre-release I'm about to release today that includes the Matrox G200 KMS driver will also fix the blank screen on this server too.

**Comment by PartialVolume** [comment]
@Cody-Coleman @OlivierFrancais @GrimDemon @chmuri Can you try the latest pre-release which now has the Matrox G200 KMS DRM drivers, which these Dell servers use. In addition I also added the AST server drivers. Hopefully if all works well, this should fix the blank screen issue. 

[Pre-release Details](https://github.com/PartialVolume/shredos.x86_64/releases/tag/v2021.08.2_23.5_x86-64_0.34)

[.img file for burning to USB](https://github.com/PartialVolume/shredos.x86_64/releases/download/v2021.08.2_23.5_x86-64_0.34/shredos-2021.08.2_23.5_x86-64_0.34_20230702.img)

**Comment by OlivierFrancais** [comment]
I tried on R440 and R650xs with the new img, same result. I see Booting 'shredos', the loader going to 100% and nothing after. I'm stuck on this, nothing blink, no tty. I'm using USB 3.0, if it can help

**Comment by PartialVolume** [comment]
@OlivierFrancais If  you've not already tried this can you append nomodeset to the linux command line in /EFI/BOOT/grub.cfg and also in /boot/grub/grub.cfg and rebooting.

This stops the kernel switching to DRM graphics mode.

Also, do you have the option to legacy boot on that system? On my Dell system it's F12 then I get the option to legacy boot or EFI boot.

**Comment by OlivierFrancais** [comment]
With nomodeset, it works on R440 ! But on R650xs, the nwipe UI is loading, I see the drives, but I cannot select anything, UI seems stuck or keyboard is not responsive.

**Comment by PartialVolume** [comment]
Ok, now we are getting somewhere. :-)  So the R440 has a DRM graphics issue, broken driver or some issue but works ok with the standard frame buffer.

The R650xs sounds like a missing driver for the keyboard. Is it a USB keyboard or PS2, If USB, has the R650xs got a PS2 keyboard socket. If it has and you can plug a PS2 keyboard in you will then hopefully have control of it. If that works I'll need the output of lspci, lsusb and dmesg. I can then work out if we are missing some driver.

If the R650xs doesn't have PS2 keyboard socket then if you follow the [headless login method](https://github.com/PartialVolume/shredos.x86_64#how-to-wipe-drives-on-headless-systems-or-systems-with-faulty-display-hardware-for-use-on-secure-lans-only) which will allow you to login to shredos via the network from another PC/laptop then same as before, capture the output from lspci, lsusb and dmesg and post here.

**Comment by PartialVolume** [comment]
Please reopen thsi issue if not fixed by 2023.08.2_25.0_x86-64_0.35
