### ISSUE TITLE
Other devices/drives no longer appearing

### ISSUE THREAD

**Issue by joxpUB** [PartialVolume/shredos.x86_64#13]
First, thanks for fixing that USB keyboard issue.

On the new version (v2020.02.004-0.30.001), I am unable to see any disks besides the USB drive I am booting off of. Going back to the old version, I can see them (but not wipe as the keyboard did not work).

The device I have connected is using nvme, not SATA.

**Comment by PartialVolume** [comment]
I'll be bringing out a revised version in the next few days as I incorrectly released an older kernel.

**Comment by PartialVolume** [comment]
Reverted back to v2020.02.004-0.29.006 and deleted release, while I investigate what went wrong.
