### ISSUE TITLE
Log file not created with autopoweroff

### ISSUE THREAD

**Issue by brutlern** [PartialVolume/shredos.x86_64#144]
When I use the --autopoweroff parameter, the log file is not created/saved on the USB drive. When I remove the --autopoweroff parameter, the log file is saved normally.

**Comment by PartialVolume** [comment]
Thanks for reporting, I'll fix that for the next release.

**Comment by PartialVolume** [comment]
Fixed by commit [7734422](https://github.com/PartialVolume/shredos.x86_64/commit/77344223ce8725ef2d3ff452fc454688e3b81c06). Available in pre-release [v2021.08.2_23.3_x86-64_0.34](https://github.com/PartialVolume/shredos.x86_64/releases/tag/v2021.08.2_23.3_x86-64_0.34)
