### ISSUE TITLE
Crashing on Dell Latitude 5530

### ISSUE THREAD

**Issue by jbarkley256** [PartialVolume/shredos.x86_64#164]
I'm trying to run off of Ventoy, and it has worked on older Dells, but on the 5530 (and a 5520 and 5510) it loads the .img to 100% and the computer crashes and requires a hard reboot. Tried toggling a few boot options with no effect. No legacy boot option for this model, either. Any ideas?

**Comment by PartialVolume** [comment]
Sorry, I missed you post.

What version of ShredOS are you using? Was one of the boot options you tried `nomodeset` ?

**Comment by jbarkley256** [comment]
Sorry, I switched to v2021.08.2_23.1_x86-64_0.34 and it works now.
