### ISSUE TITLE
Unable to detect internal SSD on Surface 3

### ISSUE THREAD

**Issue by jimmothy-beep** [PartialVolume/shredos.x86_64#165]
Hi there,

as mentioned in the title, Shredos is unable to detect the internal SSD regardless of how many times I restart the software.

**Comment by PartialVolume** [comment]
Hi,

What are the details? such as but not limited to

- make/model of the computer
- make/model of the SSD
- configuration, i.e how many drives on the system?
- version of ShredOS
- snapshot of what you see
- nwipe log
- etc

**Comment by PartialVolume** [comment]
Hi,

Can you post the output of lspci, that should tell me what I need to know. Thanks.

**Comment by PartialVolume** [comment]
Also, take a look in the bios and see if their is any settings for the SSD, should be AHCI mode rather than anything else like raid.

**Comment by PartialVolume** [comment]
I'm adding Microsoft Surface platform specific device drivers to the next release 2023.08.2_25.0_x86-64_0.35, due to be released imminently. Also adding ChromeOS specific hardware support.

Hopefully the Microsoft Surface specific device drivers will fix this.

**Comment by PartialVolume** [comment]
Please reopen issue if not fixed by 2023.08.2_25.0_x86-64_0.35.
