### ISSUE TITLE
Monitor says "no signal detected" after shredOS has been running for awhile [SOLVED]

### ISSUE THREAD

**Issue by lmills87** [PartialVolume/shredos.x86_64#17]
I started shredOS with default settings on a hard drive last night before I went to sleep, and when I woke up in the morning and turned my monitor on I had no signal. My HDD light was blinking in a fashion that made me think shredOS could've still been working but I have no way to know. So I just restarted my computer because there seemed to be nothing else I could do. This has happened twice now. If it matters, I've got an i9-9900K and an RTX 2080 Ti.

Is there any way I can circumvent this problem so I can wipe this drive and see confirmation of shredOS' completion?

**Comment by PartialVolume** [comment]
- Which version of ShredOS are you running?
- What method, verification and blanking are you using
- How big is the drive?
- Five minutes after the wipe started what's the ETA ?

I'm just wondering if there is some monitor power save mode that's activated that triggers after several hours.

Does pressing the B key twice bring back the display?

**Comment by PartialVolume** [comment]
Assuming you have another computer on the network that's either got a telnet client or putty if your on windows, you could telnet into ShredOS while it's running and check the nwipe log in /. You could even start a new nwipe instance in the telnet session remotely.

[how-to-wipe-drives-on-headless-systems-or-systems-with-faulty-display-hardware-for-use-on-secure-lans-only](https://github.com/PartialVolume/shredos.x86_64#how-to-wipe-drives-on-headless-systems-or-systems-with-faulty-display-hardware-for-use-on-secure-lans-only)

**Comment by PartialVolume** [comment]
If you try the telnet connection you obviously don't need to use nmap to find ShredOS's IP address, just do Alt-F2 to open another virtual terminal in ShredOS and type `ifconfig` which assuming you have plugged a ethernet lead into your device, will show ShredOS's IP address.

**Comment by PartialVolume** [comment]
One other question. What's the monitor make/model, it's not a Dell U2410 by any chance?

**Comment by lmills87** [comment]
>

**Comment by lukeman3000** [comment]
Well I accidentally closed this issue, that's embarrasing. Was trying to figure out how the "quote" function works here (it seemingly wasn't quoting anything). Oh well. To answer your questions:

`Which version of ShredOS are you running?`
version v2021.08.2_20_x86-64_0.32.014

`What method, verification and blanking are you using`
It pains me to say that, in my ignorance, I'm not sure I know what these mean. When shredOS launches I simply press "enter" on the drive I want, "S", and then "Shift+S" to confirm. So whatever settings are loaded by default, that's what I use.

`How big is the drive?`
2 TB

`Five minutes after the wipe started what's the ETA ?`
From what I can remember, I think it said somewhere around 14-16 hours remaining not too long after I started the wipe, but I can test again if you need a more accurate number.

`What's the monitor make/model, it's not a Dell U2410 by any chance?`
No, it's an Acer monitor model number XB271HU bmiprz

You said that you wondered if it's possible could be going into some kind of power save mode. I checked my monitor settings and something called "deep sleep" was enabled, so I'll turn it off and try again. But, why would this prevent the image from displaying after I started pressing buttons and such again? I did try pressing b after this happened (I think a couple times) and it didn't work. Is there some reason why disabling deep sleep on my monitor might prevent this from happening? What about turning the monitor off via the power button - could that potentially cause problems as well?

**Comment by PartialVolume** [comment]
The default settings are:
- DoD Short - The American Department of Defense 5220.22-M short 3 pass wipe (passes 1, 2 & 7).
- Last pass verify
- Blanking on.

So, I believe that's 4 complete writes to the entire disc and one verification. So in all 5 passes (read or write).

If you could change the method  and do a 'fill with zeros' instead. Leave verification as 'last pass verify'  and switch off the blanking pass. That will write zeros to the entire disc then read back the entire disc to make sure zeros were actually written. So two passes (one write, one read). The wipe time for this should be (if I've calculated correctly, quite possible I've not as I've not had my first coffee of the day yet) less than 5 hrs. This is to see if the same monitor blanking occurs on the shortest possible wipe.

In the meantime, I'll run some tests on +14 HR wipes and see if I can reproduce the problem. 

Regarding the 'deep sleep' mode, yes that's worth trying. Other people are reporting the same issue on presumably windows based systems. 

[https://community.acer.com/en/discussion/582626/acer-pradator-xb1-27-is-not-waking-up-after-sleep-mode-connected-by-hdmi-to-laptop](https://community.acer.com/en/discussion/582626/acer-pradator-xb1-27-is-not-waking-up-after-sleep-mode-connected-by-hdmi-to-laptop)

**Comment by PartialVolume** [comment]
This may also be worth reading through, including the comments. What's the connection to the monitor, HDMI, DVI or display port?

[https://www.google.com/amp/s/www.maketecheasier.com/fix-a-monitor-not-waking-up-after-sleep/%3famp](https://www.google.com/amp/s/www.maketecheasier.com/fix-a-monitor-not-waking-up-after-sleep/%3famp)

**Comment by lukeman3000** [comment]
The connection to the monitor is display port.

You were right - it apparently was deep sleep. I guess that when the monitor goes into deep sleep that input from the keyboard isn't passed back to the monitor in the same way that it is when the OS is running? In any case, disabling my monitor's deep sleep allowed me to see shredOS complete successfully. Thanks for the help!

**Comment by PartialVolume** [comment]
Excellent, glad it's working ok now. For others that may come across this thread, I'll put a summary here:

If your running Shredos and everything is working as it should but some time later you come back and find that the screen is blank, then check your monitor settings for a 'deep sleep' mode, often found on Dell and Acer monitors but maybe also other makes. **Disable 'deep sleep' mode in the monitor settings.**
