### ISSUE TITLE
ShredOS Not supporting all Intel RST RapidStore Drivers

### ISSUE THREAD

**Issue by p1r473** [PartialVolume/shredos.x86_64#174]
Hello,
I have 2 machines that ShredOS is not supporting the HD drivers so I cant shred these drives.
I cant remember which set of drivers it is but its either f6vmdflpy-x64.zip or RST_V19.1.0.1001_PV.zip (theres multple versions of these drivers and not all versions work with these drivers)
Ive uploaded the files here
[f6vmdflpy-x64.zip](https://github.com/PartialVolume/shredos.x86_64/files/13430470/f6vmdflpy-x64.zip)
[RST_V19.1.0.1001_PV.zip](https://github.com/PartialVolume/shredos.x86_64/files/13430471/RST_V19.1.0.1001_PV.zip)

**Comment by PartialVolume** [comment]
Those are windows drivers so won't work under ShredOS. As far as I know (correct me if anybody knows different), but to access those drives you will need to switch from RST to AHCI in the bios to access them under any Linux distro including ShredOS. Once wiped you can then switch back to RST if you are going to install windows or leave at AHCI if installing Linux.

**Comment by p1r473** [comment]
Darn , thank you

**Comment by p1r473** [comment]
@PartialVolume so the bios is currently set to AHCI
So these are just two SSDs that can be normally wiped with shredos but can't be seen when raided
However, I believe I should still be able to see the two drive separately to wipe them separate and ignore the raid array
Any idea?

**Comment by PartialVolume** [comment]
If you login to a virtual terminal in ShredOS and check if there is a /etc/mdadm/mdadm.conf ?

If you type `sudo mdadm` is the program installed?

**Comment by PartialVolume** [comment]
I just checked, mdadm is not installed. Thing is I don't know whether it is required to see the Intel RST drives as normal drives or not. I wouldn't have thought so as it's normally used to configure raid which we don't want. In your bios is there a third option, AHCI, RAID and ?? or only those two?. Maybe mdadm needs to be installed and configured in a non raid state. Unfortunately I don't know enough about these drives. Maybe somebody else can offer some advice.

**Comment by PartialVolume** [comment]
Just wondering but do you have something like this in your bios?
![image](https://github.com/PartialVolume/shredos.x86_64/assets/22084881/34f1a225-ef7f-45e0-8adb-6ba356a7b65e)

**Comment by p1r473** [comment]
Nope no option in bios for changing or modifying the raid

**Comment by Firminator** [comment]
What laptop model or PC motherboard do you have? BIOS or UEFI?
There *should* be an option to disable the RST and just use AHCI/non-RAID mode like PartialVolume said. Also you can invoke the RST menu seen on the screenshot by pressing CTRL+I or CTRL+R during POST if I recall correctly (it's been over a decade when I last seen an RST enabled device). It might be hidden in one of the submenus of the BIOS.
