### ISSUE TITLE
[Solved] USB has gone AWOL when ShredOS attempts to write PDF docs & configs. Hardware issue, USB driver or just cheap USB stick?

### ISSUE THREAD

**Issue by PartialVolume** [PartialVolume/shredos.x86_64#181]
Interesting problem that I've not come across before, related to a USB flash drive, that incidentally only cost about £2.50 ($2) each.

I have been booting off these cheap USB sticks without any issues but last night did an overnight wipe for the first time using one of these sticks. Probably about 12 hrs between me starting the wipe and hitting the space-bar on successful completion. ShredOS then says it can't find the USB exFAT/FAT32 drive which was indeed correct. I switched to the virtual terminal ALT F2 and typed fdisk -l. Sure enough the USB drive was missing.

So I then unplugged the drive and plugged it into the same USB port, fdisk -l still says it's missing. dmesg confirms I unplugged it and plugged it back in but it can't enumerate it. So I plug it into a different USB port on the same machine and it works ! confirmed by fdisk -l and dmesg.

As I hadn't powered down the computer I was still able to restart nwipe, i.e. the 4,3,2,1 countdown and then after nwipe was displayed I immediately CONTROL C, ShredOS then wrote the PDF's, configs, logs and dmesg back to the USB stick without any further problem.

So in summary, if for some reason ShredOS complains that it can't find a exFAT/FAT32 partition, check that it is really missing using `fdisk -l` then unplug the USB stick and plug it into a different port, give it 10 seconds for linux to recognise it's there then restart nwipe 4,3,2,1 then once nwipe has displayed, CONTROL C to abort. The PDF, logs etc should then be copied across successfully.

I'm 99.9% sure this is nothing to do with nwipe/shredOS but either the cheap $2 USB stick shutting itself down after many hours of inactivity or the USB drivers shutting the port down or maybe it's just quirky hardware or drivers.

Anybody else ever seen this?

I'll repeat this same wipe tonight with a vastly! more expensive Corsair USB flash drive and let you know the result.

------------
Hardware was a DELL Optiplex 9020 running the latest master copy of ShredOS. USB drives were unbranded Chinese sticks.

**Comment by fieldofgreen** [comment]
I have not seen that happen yet, Unrelated to ShredOS I have had Cheap PNY 32 GB drives around the office just decide to fail for no reason in particular, essentially wiping itself and ruining the USB drive. Its done it with just files on it (the folder would become a .file and therefore useless), when set up as a windows 10 boot disk (it just refuses to be recognized as a formatted drive forcing you to format it and will repeatedly fail from then on) and some other tasks. So I wouldnt put it past cheap USB drives to behave strangely

**Comment by PartialVolume** [comment]
The Corsair USB stick worked fine. Again around 12 hours between boot and successful completion. All the files wrote to the Corsair without any issues.

Think I'll put this issue down to the cheap USB stick for the time being.
