### ISSUE TITLE
Set IP address on ShredOS

### ISSUE THREAD

**Issue by flhoest** [PartialVolume/shredos.x86_64#186]
I need to setup an IP address on my SHredOS box.
I booted the SHredOS IMG remotely using IPMI to completely shred a 7 HDDs server before shipping. I have the reports on the filesystem and I need to scp them to a remote location for reference.
I used the 2nd terminal (ALT+F2) and I'm abe to type some commands. I've tried to add an IP using ip address add command, but I can't seem to have it working.
Anyone if facing similar issues ?
Thanks.

**Comment by PartialVolume** [comment]
I assume you mean it's saved to the non persistent filesystem that held in memory. If so what ever you do don't switch it off or reboot ShredOS other wise you will lose any logs/pdfs.

If you just want to get the logs/pdfs off I would plug a USB stick in and get them off that way by control C on nwipe which will save to the first FAT32 formatted USB  stick, preferably a ShredOS stick.You can then start setting static IP addresses.

I've never tested with scp or booted via IPMI? So can't help much.

**Comment by PartialVolume** [comment]
What version of ShredOS?

**Comment by flhoest** [comment]
Yes you are right, I'm in the process of wiping a few disks and it runs for another 40 hours ... so in // I'm trying access the file system from the outside world to expatriate the files in a safe place. I'm running the latest version I guess ? This is v2023.08.2_25.0_x86-64_0.35.
I have no means to plug any stick in the server. The machine is 7000 kms away from me :)
It would be nice to add option to select a network interface and set IP settings on it, so the process is seamless and very easy for sending reports out.

**Comment by PartialVolume** [comment]
Isn't the dynamic IP any good for you?

**Comment by flhoest** [comment]
That's the issue, we do not use DHCP in our datacenter. We have fixed IP assigned on demand and open in the firewall.

**Comment by PartialVolume** [comment]
I'm on the road today so may not be able to help much. So how are you accessing the system at the moment, can you access virtual terminals, are you telneted in?

**Comment by flhoest** [comment]
I'm using the remote console in HTML5 provided by the Supermicro BMC. I have mounted the ShredOS IMG on a virtual drive. I'm in a virtual terminal using CLI trying to set an IP on the machine, I have 4 interfaces and trying to find the one with the link and correct VLAN ...

**Comment by PartialVolume** [comment]
Ok, so are you running these sort of commands?
```
auto eth0
allow-hotplug eth0
iface eth0 inet static
address 192.168.0.1
netmask 255.255.255.0
```

**Comment by flhoest** [comment]
No, I'm playing with ip addr add dev eth1 ..... up link show, etc ...

**Comment by flhoest** [comment]
It looks like I need to setup a VLAN ... that's my issue ;)

**Comment by flhoest** [comment]
vconfig add says package not installed ...
it looks like these type of setup is not supported with the packages/libraries provided by ShredOS ...
I will try to go back to native VLAN instead ...

**Comment by flhoest** [comment]
Ok, I managed to have IP connectivity. But the options for transferring the files are .... almost non existent ;)

**Comment by PartialVolume** [comment]
Have you got or can setup a FTP server on your network? so you could use lftp to send.

**Comment by flhoest** [comment]
Ok, I managed to get the report using ftp .... great ! We can close this issue I have all the commands to apply IP address.
But, the feature request is still valid ! Having a network configuration UI in the menu would be awesome ;)

**Comment by flhoest** [comment]
@PartialVolume message crossing ;)

**Comment by PartialVolume** [comment]
Just out of interest what were the commands you used?

**Comment by PartialVolume** [comment]
>Having a network configuration UI in the menu would be awesome ;)

I can add that option.

**Comment by flhoest** [comment]
```
ip addr add <ip_address/mask> dev <interface>
ifconfig <dev> up
```

then make sure the interface is in the correct VLAN.
I do not need DNS or default gateway at this stage since my FTP server is in the same subnet.
