### ISSUE TITLE
Icon & autorun.inf & readme

### ISSUE THREAD

**Issue by miharix** [PartialVolume/shredos.x86_64#19]
Hi,

I noticed that ShredOS USB has no icon and basic description when plug in windows.

Because it could be unpleasant surprise if IT made "--autonuke --nowait" _(btw works great!)_ and then lost or forgot the USB.
 Some "lucky" finder could connect to his PC, found no info in USB,
  forgot there and rebooted, and have(known or unknown) USB in boot order

Don't know if this project has some official logo, so I made 5 versions by quickly combining icons from https://remixicon.com/
_( I'm not a designer )_
![5_ideas](https://user-images.githubusercontent.com/5471326/104908641-0f795900-5987-11eb-87da-e1a49f613fa7.png)
Added autorun.inf -> icon + drive name changes to "ShredOS - DANGER"
Also added minimal description

[shred_OS_icon.zip](https://github.com/PartialVolume/shredos.2020.02/files/5829691/shred_OS_icon.zip)

![example](https://user-images.githubusercontent.com/5471326/104906821-7ba68d80-5984-11eb-960e-63a0abc03e52.png)

![USB_root](https://user-images.githubusercontent.com/5471326/104906929-9ed13d00-5984-11eb-90a5-ab76f2cd546a.png)

**Comment by PartialVolume** [comment]
I like it, this is my preferred icon, looks like it might be yours too.  I'll make your suggested changes ready for the next release. Thanks for the input. Think that would look good in the README.md file too.

![shred_db](https://user-images.githubusercontent.com/22084881/104947827-3d28c700-59b4-11eb-80a7-4f7a5ef78031.png)
