### ISSUE TITLE
[Solved] Keyboard map layout not identified

### ISSUE THREAD

**Issue by Ricky-Tigg** [PartialVolume/shredos.x86_64#192]
**v.:** _2023.08.2_25.0_x86-64_0.35_. Disk image (_img_) on Ventoy-formatted media for UEFI. Hello.

### In running Linux distribution –Fedora, edition 39.
Keyboard layout:
```
$ localectl status
System Locale: LANG=fi_FI.UTF-8
 VC Keymap: fi
 X11 Layout: fi
```
### In running ShredOS
In virtual console: <kbd>ctrl</kbd> <kbd>alt</kbd> <kbd>f2</kbd>; `sh-5.2#` prompt exhibited.
- Steps to reproduce
1. Set the appropriate keyboard map for the current session – `loadkeys fi`.
1. Test the effectiveness of step _1._ by pressing Scandinavian keys <kbd>Å</kbd>, <kbd>Ä</kbd> and <kbd>Ö</kbd>, and observe the result for each of them.

  - Observed results:
<kbd>Å</kbd> and <kbd>Ä</kbd> | characters not printed.
<kbd>Ö</kbd> | prompt changed to `(arg: 6)`, character not printed.

Therefore the keyboard map layout is not identified.

**Comment by PartialVolume** [comment]
On the current version we only have us_en.UTF8, POSIX and C locales installed.

I'll update ShredOS with more locales in the next update, which will include your locale fi_FI.UTF-8

**Comment by Ricky-Tigg** [comment]
According to the plan, this task could be completed by now, and I have no reasonable doubt that it is. However, in the unlikely event that it is not yet, and that in this state it is promised to remain, it would be up to the rest of the world, which is therefore represented by a _Keymap_ other than _en_ for the _en_US.UTF8_ locale, to seek for a valid alternative software, which simply supports any other _Keymap_. Thus **making the application usable** – but then, isn't that the very essence of any application?

**Comment by PartialVolume** [comment]
I'm not sure exactly when it was updated with more keymaps but as per the README.md document I added some help at the time. [Setting the locale keymap](https://github.com/PartialVolume/shredos.x86_64?tab=readme-ov-file#how-to-set-the-keyboard-map-using-the-loadkeys-command-see-here-for-persistent-change-between-reboots)

**Comment by Ricky-Tigg** [comment]
You have to see it to believe it. Such complexity to define a keyboard map would probably be to its advantage in the context of a technical demonstration competition. But in the use for which this application is intended, it makes it a dubious practice, likely to put off an audience, who will certainly conclude that it is not worth using. However, in my experience, finding a well-designed model representative in relation to this subject is hardly a miracle; for example, OpenBSD is one. For it, the system console driver defaults to standard _US_ keyboard map. But unlike this application, each of the keyboard maps made available can be activated by **simple selection**.

**Comment by PartialVolume** [comment]
I'm looking forward to receiving you pull requests 🙂
