### ISSUE TITLE
How to USB boot on Asus Rog duo 16 g650pz

### ISSUE THREAD

**Issue by Killahax** [PartialVolume/shredos.x86_64#259]
I'm on a Asus Rog duo 16 g650pz,

I change boot sequence to usb #1 slot.
![bios](https://github.com/PartialVolume/shredos.x86_64/assets/149981353/fb3abfb8-fdff-4b13-ba5a-5152cbe4d8f9)

Then save and exit. But it doesn't boot from usb, goes straight to main ssd. Now on my msi I did this exactly and worked 100%, but not on my asus duo. What am I doing wrong?

I also disabled secure boot control in bios " Asus duo"  save and exit. But secure boot control goes back to enabled. 
![bios 2](https://github.com/PartialVolume/shredos.x86_64/assets/149981353/54e880da-a27a-4a17-a64b-ff2a39175ecb)

Wondering if it has to do with these keys? 
![bios 3](https://github.com/PartialVolume/shredos.x86_64/assets/149981353/e0200d7e-ab12-4f11-83cb-609ee18ae101)

Here is my shredos usb drive:
![Screenshot 2024-07-03 010116](https://github.com/PartialVolume/shredos.x86_64/assets/149981353/39ce3dc1-92bb-41f8-aad6-d8b5aeb85bb4)
![Screenshot 2024-07-03 010128](https://github.com/PartialVolume/shredos.x86_64/assets/149981353/94bd8e92-3159-4d10-acb1-b21c0ddcbe4e)

Would greatly appreciate your input.

**Comment by PartialVolume** [comment]
Looks like you are doing everything correctly. Have you tried accessing the boot menu? Disable secure boot and save & exit, then power down, hold ESC key down while powering up release when bios screen appears. Does it give you a boot selection menu that shows main disc and USB to select from?

**Comment by Killahax** [comment]
I'll give that a try thank you

**Comment by Killahax** [comment]
> Looks like you are doing everything correctly. Have you tried accessing the boot menu? Disable secure boot and save & exit, then power down, hold ESC key down while powering up release when bios screen appears. Does it give you a boot selection menu that shows main disc and USB to select from?

worked perfect thank you.

**Comment by PartialVolume** [comment]
> > Looks like you are doing everything correctly. Have you tried accessing the boot menu? Disable secure boot and save & exit, then power down, hold ESC key down while powering up release when bios screen appears. Does it give you a boot selection menu that shows main disc and USB to select from?
> 
> worked perfect thank you.

That's great 👍
