### ISSUE TITLE
Package Request: Add parallel to allow multiple sg_format commands at the same time

### ISSUE THREAD

**Issue by fthobe** [PartialVolume/shredos.x86_64#274]
There are several sg_format or hdparm operations that make sense to be executed in parallel, for example the formating of a set of multiple disks at the same time as outlined here: [Remove Integrity Protection](https://github.com/gms-electronics/formatingguide/blob/main/removeintegrityprotection.md)

The inclusion of parallel would only add 324.4 KB to the iso as all required dependencies are already present: 

1. [perl](https://archlinux.org/packages/core/x86_64/perl/)
2. [procps-ng](https://archlinux.org/packages/core/x86_64/procps-ng/)

**Comment by PartialVolume** [comment]
Yes, I can add parallel to ShredOS. Were to thinking of submitting a PR or do you want me to do it?

**Comment by fthobe** [comment]
I never used arch with buildroot, if you give me some hints I can do a pull request later today, I am in Asia right now so it's still early

Does this guide cover all bases? 

https://buildroot.org/downloads/manual/manual.html#adding-packages

**Comment by fthobe** [comment]
I am not sure I did it right, but take a look and tell me.
I created the folder and files in the package directory including: 
1. parallel Folder in Package
2. package/parallel/config.in
3. package/parallel/packageparallel.hash
4. package/parallel/parallel.mk
5. added the package to /package/Config.in
6. added the package to shredos_defconfig (which i assumed is used to generate .config)

**Comment by PartialVolume** [comment]
Looks like all the correct files have been changed. Sounds like you manually made those changes, was parallel not in packages using make menuconfig or make busybox?

I'll download your branch and build it later today.

**Comment by fthobe** [comment]
Hey, I am not deep into the Linux embedded world so it was a first for me. I pieced it together using other packages and a commit for a package you made in the past. If you have some useful links I am happy to take a look at them!

**Comment by fthobe** [comment]
@PartialVolume I should have fixed literally everything and I was successful building it.
