### ISSUE TITLE
Shutdown / --autopoweroff  is broken

### ISSUE THREAD

**Issue by betaprinz** [PartialVolume/shredos.x86_64#30]
my grub.cfg entry:

menuentry "ShredOS-ZERO-NoUSB-AutoOFF-AllDrives" {
	linux /boot/shredos console=tty3 loglevel=3 loadkeys=de nwipe_options="--method=zero --verify=off --noblank --nousb --autonuke --autopoweroff"
}

After wipping my disk i get a error/message 

"shutdown: -H and -P flags can only be used along with -h flag".
...
...
...

"Paused, press any key to restart nwipe."

Any Ideas?

**Comment by PartialVolume** [comment]
@betaprinz Interesting, shutdown -P (which is what nwipe uses in it's code) works on Ubuntu 18.04LTS without any issues. I'll check it out on buildroot (ShredOS) and keep back to you this afternoon.

**Comment by PartialVolume** [comment]
@betaprinz Confirmed, we have two different versions of the shutdown command that behave slightly differently.

The shutdown command that nwipe uses is `shutdown -P +1 "Broadcast shutdown message"`. This works fine on Ubuntu 18.04 LTS but. as you found, on ShredOS fails with the error `shutdown: -H and -P flags can only be used along with -h flag".`

Luckily there is a shutdown command with options that work correctly on both ShredOS and Ubuntu 18.04 LTS, this is `shutdown -Ph +1 "Broadcast shutdown message"`. i.e with the addition of -h.

I'll make the changes to nwipe and once that's done I'll release another version of ShredOS.

Thanks for reporting the problem.

**Comment by PartialVolume** [comment]
Fixed by #37
